version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    restart: always
    container_name: server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  pgdbdata: null
